# Generated by Django 4.0.6 on 2022-07-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_users_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='CurrentChallenge',
            fields=[
                ('launched_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.users')),
                ('name', models.CharField(max_length=30)),
                ('date_start', models.DateField(auto_now_add=True)),
                ('progress', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.challenges')),
            ],
        ),
    ]
