# Generated by Django 4.0.6 on 2022-07-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='main_copy',
            field=models.BooleanField(default=True),
        ),
    ]
