# Generated by Django 4.0.6 on 2022-07-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_challenges_main_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
    ]
