# Generated by Django 4.0.6 on 2022-07-12 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_challenges_for_all_exercise_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentchallenge',
            name='exercise_id',
        ),
        migrations.AddField(
            model_name='currentchallenge',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.exercise'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='main_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='measurement',
            field=models.CharField(choices=[('numbers', 'количество'), ('distance', 'расстояние, Км'), ('minutes', 'минуты')], default='number', max_length=30),
        ),
    ]
