# Generated by Django 4.0.6 on 2022-07-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_currentchallenge_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentchallenge',
            name='exercises_done',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
